name: Build and Deploy Angular

on:
    push: 
      branches:
      - main

    workflow_dispatch:
      inputs:
       environments:
       descriptions: Select the Environment to deploy
       options:
         - dev
         - int
         - prod
         

jobs:
    build-deploy:
      runs-on: ubuntu-latest

      steps:
        -name: Checkout
        uses: actions/checkout@v4
