name: Build and Deploy Angular

on:
  push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20  

      - name: Install Dependencies
        run : npm install
        
      - name: Build Angular App
        run : npm run build
        
      - name: Archieve Production Artifacts
        uses : actions/upload-artifact@v4
        with : 
          name : Angular-Builded
          path : |
            dist
            !dist/**/*.md

      # - name: Deploy to gh page
      #   run : |
      #       npx angular-cli-ghpages --dir=dist/angular-gihub-actions
      #   env: 
      #       CI: true
      #       GH_TOKEN: ${{ secrets.GH_TOKEN }}      
